"""followers

Revision ID: 06653dfb8c8a
Revises: e45f9bc388d2
Create Date: 2021-01-01 17:23:05.569589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06653dfb8c8a'
down_revision = 'e45f9bc388d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
